#!/usr/bin/env node

const fs = require('fs')
const { resolve } = require('path')
const { program } = require('commander')
const inquirer = require('inquirer')
const { asyncRun } = require('./dist/utils/async-run')
const { loadConfig } = require('./dist/utils/load-config')
const { Migoose } = require('./dist')

const config = loadConfig()

if (!fs.existsSync(config.dir)) {
  fs.mkdirSync(config.dir)
}

asyncRun(async () => {
  program
    .name('Migoose CLI')
    .description('Mongoose Migration Toolkit')
    .version('1.0.0')

  program
    .command('create')
    .description('Creates a migration file')
    .action(async () => {
      const prompt = await inquirer.prompt({
        name: 'name',

        type: 'input',
        message: `What is the name of the new migration?`,
      })

      await Migoose.createFile(prompt.name)

      console.log(`Migration created!`)
    })

  await program.parseAsync(process.argv)
})
